import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./components/navbar/Navbar"
import Footer from "./components/footer/Footer"
import ResponsiveContainer from "./components/responsiveContainer/ResponsiveContainer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <title>Titan Capital</title>
      </head>
      <body className={inter.className}>
        <ResponsiveContainer>
          <Navbar />
        </ResponsiveContainer>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
